### ISSUE TITLE
Problem with Elasticsearch datasource

### ISSUE THREAD

**Issue by fsa1803** [marcusolsson/grafana-hourly-heatmap-panel#6]
I am using this panel with ES datasource (Grafana 7.0.3) but don't show heatmap.
![img04](https://user-images.githubusercontent.com/66841577/88311764-9966a300-cd11-11ea-9a86-3d8f75c424f9.PNG)

Tooltip show corret values:
![img05](https://user-images.githubusercontent.com/66841577/88312789-de3f0980-cd12-11ea-9f57-ef622ce35f17.PNG)
![img06](https://user-images.githubusercontent.com/66841577/88312803-e1d29080-cd12-11ea-8d18-b4146ffab319.PNG)

Thanks

**Comment by glynternet** [comment]
@fsa1803 what version of the heatmap panel are you using?

Your issue looks similar to what I was having in https://github.com/marcusolsson/grafana-hourly-heatmap-panel/issues/1 which was fixed by https://github.com/marcusolsson/grafana-hourly-heatmap-panel/pull/2

@marcusolsson is this fix included in the latest release?

**Comment by fsa1803** [comment]
I was using version 0.3.1, now I have updated to 0.3.2. but the problem remains.

![img07](https://user-images.githubusercontent.com/66841577/88525535-fe184b00-cffa-11ea-8c11-bde9cfc24c8a.PNG)

**Comment by marcusolsson** [comment]
Hi @fsa1803! I've published 0.4.1 with the recent changes. Let me know if the problem remains!

**Comment by fsa1803** [comment]
With new version the problem is resolved.

Thanks.
